## 1️⃣ Setup

### 1.1) Imports

In [1]:
import pandas as pd
import numpy as np


# Import for special characters (Mojibake)
from ftfy import fix_text

### 1.2) Get the data 📕

The data is available on Kagle, but on our case it was downloaded and saved inside **folder raw_data** as **winemag-data-130k-v2.csv**

In [2]:
# Data pulled into a Pandas DataFrame

df = pd.read_csv('../raw_data/winemag-data-130k-v2.csv')
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

### 1.3) Have a look at the data 🔎

In [ ]:
# Check the non-null count and data types for each column

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

## 2️⃣ Preprocessing

## 2.1) Check missing values

In [6]:
# Check number of missing values in each column
df.isna().sum()

Unnamed: 0                   0
country                     63
description                  0
designation              37465
points                       0
price                     8996
province                    63
region_1                 21247
region_2                 79460
taster_name              26244
taster_twitter_handle    31213
title                        0
variety                      1
winery                       0
dtype: int64

In [5]:
# Check the % of missing values in each column, rounded by 2 decimal places.

(df.isna().mean() * 100).round(2)

Unnamed: 0                0.00
country                   0.05
description               0.00
designation              28.83
points                    0.00
price                     6.92
province                  0.05
region_1                 16.35
region_2                 61.14
taster_name              20.19
taster_twitter_handle    24.02
title                     0.00
variety                   0.00
winery                    0.00
dtype: float64

## 2.2) Check duplicated rows

In [ ]:
# Duplicated rows based on description text and title
dups = df[df.duplicated(subset=["title", "description"], keep=False)]

print("Duplicated rows based on description and title:", dups.shape[0])

Duplicated rows based on description and title: 19966

In [ ]:
# Drop duplicates based on description and title.

before = len(df)
wine_clean = df.drop_duplicates(subset=["title", "description"])
after = len(wine_clean)
print(f"Duplicate rows removed: {before - after}")

Duplicate rows removed: 9983

## 2.3) Fix mojibake (accent corruption)

In [12]:
# All the columns with text data types will be converted to string and cleaned using the fix_text function from the ftfy library.
# This will help to correct any mojibake or encoding issues in the text data.
# When it converts to string the empty values will be converted to 'nan' string, so we will convert them to NaN after the fix_text function is applied.


# Create list with all Object columns (text columns) in the DataFrame
text_cols = [
    'country', 'description', 'designation', 'province',
    'region_1', 'region_2', 'taster_name', 'taster_twitter_handle',
    'title', 'variety', 'winery'
]

# convert all text columns to string and apply fix_text function
for col in text_cols:
    wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)

# Convert 'nan' strings back to NaN
wine_clean = wine_clean.replace('nan', np.nan)

/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)
/tmp/ipykernel_44846/1343303227.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  wine_clean[col] = wine_clean[col].astype(str).apply(fix_text)

## 2.4) Drop columns that will not be need it

In [ ]:
 """Drop columns not used by the recommender: region_2, taster_twitter_handle"""

 wine_clean = wine_clean.drop(columns = ["region_2", "taster_twitter_handle"])

## 2.2) Rename first collumn as index

In [ ]:
# Rename Unnamed: 0 collumn as index

df_clean = w.rename(columns={"Unnamed: 0": "index"})

df_clean.columns

## 2.3) Fix mojibake (accent corruption)

In [ ]:
# All the columns with text data types will be converted to string and cleaned using the fix_text function from the ftfy library.
# This will help to correct any mojibake or encoding issues in the text data.
# When it converts to string the empty values will be converted to 'nan' string, so we will convert them to NaN after the fix_text function is applied.


# Create list with all Object columns (text columns) in the DataFrame
text_cols = [
    'country', 'description', 'designation', 'province',
    'region_1', 'region_2', 'taster_name', 'taster_twitter_handle',
    'title', 'variety', 'winery'
]

# convert all text columns to string and apply fix_text function
for col in text_cols:
    df_clean[col] = df_clean[col].astype(str).apply(fix_text)

# Convert 'nan' strings back to NaN
df_clean = df_clean.replace('nan', np.nan)

In [13]:
wine_clean[wine_clean['country'] == 'Portugal'].sample(10)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
101675,101675,Portugal,"A bold, ripe, perfumed wine with Baga tannins ...",Encontro,90,18.0,Bairrada,NaN,NaN,Roger Voss,@vossroger,Global Wines 2011 Encontro Baga (Bairrada),Baga,Global Wines
106930,106930,Portugal,This is a classic crisp apple-driven and fruit...,Escolha,87,10.0,Vinho Verde,NaN,NaN,Roger Voss,@vossroger,Quinta da Lixa 2016 Escolha White (Vinho Verde),Portuguese White,Quinta da Lixa
124573,124573,Portugal,Get past the pharmacy aromas and this is a ple...,Cister da Ribeira Branco,83,10.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta de Ventozelo 2009 Cister da Ribeira Bra...,Portuguese White,Quinta de Ventozelo
25137,25137,Portugal,"Grassy, herbaceous wine, with citrus and goose...",Dourosa Branco,86,NaN,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta de la Rosa 2010 Dourosa Branco White (D...,Portuguese White,Quinta de la Rosa
14023,14023,Portugal,"This is a fresh and fruity wine, full of red f...",Passadouro Porto Tawny Reserve,88,19.0,Port,NaN,NaN,Roger Voss,@vossroger,Quinta do Passadouro NV Passadouro Porto Tawny...,Port,Quinta do Passadouro
15044,15044,Portugal,"A soft, fruity wine, with spice, strawberry an...",Twisted,88,18.0,Douro,NaN,NaN,Roger Voss,@vossroger,Niepoort 2009 Twisted Red (Douro),Portuguese Red,Niepoort
20981,20981,Portugal,"Syrah and Trincadeira, both known to be spicy,...",Smart Dog Syrah-Trincadeira,85,10.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,J. Portugal Ramos 2016 Smart Dog Syrah-Trincad...,Portuguese Red,J. Portugal Ramos
61431,61431,Portugal,Smooth Chardonnay-like richness gives concentr...,Branco Reserva,90,50.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta do Vallado 2009 Branco Reserva White (D...,Portuguese White,Quinta do Vallado
16671,16671,Portugal,Produced from high altitude vineyards to retai...,Evel Branco,85,13.0,Douro,NaN,NaN,Roger Voss,@vossroger,Real Companhia Velha 2014 Evel Branco White (D...,Portuguese White,Real Companhia Velha
117874,117874,Portugal,"As part of its top varietal range, Esporão has...",PV,92,35.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade do Esporão 2008 PV Petit Verdot (Alent...,Petit Verdot,Herdade do Esporão

## DONE UNTIL HERE:::NEED TO ANALYSE BETTER AFTER THIS

In [ ]:
df_clean.sample(10)

In [ ]:
df_clean[df_clean['country'] == 'Portugal'].sample(10)

## 2.4 Handle missing values

In [ ]:
# Check the % of missing values in each column, rounded by 2 decimal places.

(df_clean.isna().mean() * 100).round(2)

# 2.4.1 - Price Column

In [ ]:
# For Price the null values will be replace by 0
df_clean['price'] = df_clean['price'].fillna(0)

df_clean[df_clean["price"].isna()]

# 2.4.2 - Taster_name Column

In [ ]:
# For taster_name the null values will be replace by 'unknown'
df_clean['taster_name'] = df_clean['taster_name'].fillna('unknown')

df_clean[df_clean["taster_name"].isna()]

# 2.4.3 - Country Column

In [ ]:
# For the country the null values will be replace according with the winery Location.
df_clean.loc[df_clean["winery"] == "Gotsa Family Wines", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Barton & Guestier", "country"] = "France"
df_clean.loc[df_clean["winery"] == "Kakhetia Traditional Winemaking", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Tsililis", "country"] = "Greece"
df_clean.loc[df_clean["winery"] == "Ross-idi", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "Les Frères Dutruy", "country"] = "Switzerland"
df_clean.loc[df_clean["winery"] == "El Capricho", "country"] = "Spain"
df_clean.loc[df_clean["winery"] == "Büyülübağ", "country"] = "Turkey"
df_clean.loc[df_clean["winery"] == "Psagot", "country"] = "Israel"
df_clean.loc[df_clean["winery"] == "Orbelus", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "St. Donat", "country"] = "Hungary"
df_clean.loc[df_clean["winery"] == "Familia Deicas", "country"] = "Uruguay"
df_clean.loc[df_clean["winery"] == "Bartho Eksteen", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Stone Castle", "country"] = "Kosovo"
df_clean.loc[df_clean["winery"] == "Teliani Valley", "country"] = "Georgia"
df_clean.loc[df_clean["winery"] == "Undurraga", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Mt. Beautiful", "country"] = "New Zealand"
df_clean.loc[df_clean["winery"] == "Neumeister", "country"] = "Austria"
df_clean.loc[df_clean["winery"] == "Bachelder", "country"] = "Canada"
df_clean.loc[df_clean["winery"] == "Chilcas", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Santa Ema", "country"] = "Chile"
df_clean.loc[df_clean["winery"] == "Newton Johnson", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Ktima Voyatzi", "country"] = "Greece"
df_clean.loc[df_clean["winery"] == "Lismore", "country"] = "South Africa"
df_clean.loc[df_clean["winery"] == "Logodaj", "country"] = "Bulgaria"
df_clean.loc[df_clean["winery"] == "Somlói Vándor", "country"] = "Hungary"
df_clean.loc[df_clean["winery"] == "Amiran Vepkhvadze", "country"] = "Georgia"

df_clean[df_clean["country"].isna()]

In [ ]:
df_clean["country"].unique()

In [ ]:
# Ckeck how many non.null per column
df_clean.info()


# Check the % of missing values in each column, rounded by 2 decimal places.
(df_clean.isna().mean() * 100).round(2)

In [ ]:
df_clean[df_clean["province"].isna()]

In [ ]:
df_clean[df_clean['winery'] == 'Familia Deicas']