## 1️⃣ Setup

### 1.1) Imports

In [26]:
import pandas as pd


# Import for special characters (Mokibake)
from ftfy import fix_text

### 1.2) Get the data 📕

The data is available on Kagle, but on our case it was downloaded and saved inside **folder raw_data** as **winemag-data-130k-v2.csv**

In [27]:
# Data pulled into a Pandas DataFrame

df = pd.read_csv('../raw_data/winemag-data-130k-v2.csv')
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [28]:
# Check the non-null count and data types for each column

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             129971 non-null  int64
 1   country                129908 non-null  object
 2   description            129971 non-null  object
 3   designation            92506 non-null   object
 4   points                 129971 non-null  int64
 5   price                  120975 non-null  float64
 6   province               129908 non-null  object
 7   region_1               108724 non-null  object
 8   region_2               50511 non-null   object
 9   taster_name            103727 non-null  object
 10  taster_twitter_handle  98758 non-null   object
 11  title                  129971 non-null  object
 12  variety                129970 non-null  object
 13  winery                 129971 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 13.9+ MB

## 1.3 Remove useless columns

In [30]:
# Remove Unnamed: 0 collumn
df_clean = df.drop(columns=['Unnamed: 0'])
df_clean.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'taster_name', 'taster_twitter_handle', 'title',
       'variety', 'winery'],
      dtype='object')

## 1.4 Handle missing values

In [ ]:
# For Price the null values will be replace by 0
df_clean['price'] = df_clean['price'].fillna(0)

# For taster_name the null values will be replace by 'unknown'
df_clean['taster_name'] = df_clean['taster_name'].fillna('unknown')




df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  129971 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            129971 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 12.9+ MB

In [35]:
df_clean[df_clean['country'].isna()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,0.0,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi
...,...,...,...,...,...,...,...,...,...,...,...,...,...
124176,NaN,This Swiss red blend is composed of four varie...,Les Romaines,90,30.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Les Frères Dutruy 2014 Les Romaines Red,Red Blend,Les Frères Dutruy
129407,NaN,Dry spicy aromas of dusty plum and tomato add ...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Cabernet Sauvignon,Cabernet Sauvignon,El Capricho
129408,NaN,El Capricho is one of Uruguay's more consisten...,Reserve,89,22.0,NaN,NaN,NaN,Michael Schachner,@wineschach,El Capricho 2015 Reserve Tempranillo,Tempranillo,El Capricho
129590,NaN,"A blend of 60% Syrah, 30% Cabernet Sauvignon a...",Shah,90,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Büyülübağ 2012 Shah Red,Red Blend,Büyülübağ
129900,NaN,This wine offers a delightful bouquet of black...,NaN,91,32.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Psagot 2014 Merlot,Merlot,Psagot

In [39]:
df_clean[df_clean['winery'] == 'Barton & Guestier']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
2789,France,"Soft and fruity with some sweetness, this red-...",Bistro,84,8.0,France Other,Ile de Beauté,NaN,Roger Voss,@vossroger,Barton & Guestier 2011 Bistro Pinot Noir (Ile ...,Pinot Noir,Barton & Guestier
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,0.0,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier
5946,France,This wood-laden wine has light berry fruit and...,NaN,84,10.0,Bordeaux,Bordeaux,NaN,Roger Voss,@vossroger,Barton & Guestier 2008 Bordeaux,Bordeaux-style Red Blend,Barton & Guestier
5955,France,"Soft, lightly creamy Chardonnay, pleasantly fr...",NaN,84,10.0,Burgundy,Mâcon-Villages,NaN,Roger Voss,@vossroger,Barton & Guestier 2009 Mâcon-Villages,Chardonnay,Barton & Guestier
5956,France,"The wine is still very young, revealing sweetn...",Thomas Barton Réserve,84,25.0,Bordeaux,Sauternes,NaN,Roger Voss,@vossroger,Barton & Guestier 2009 Thomas Barton Réserve ...,Bordeaux-style White Blend,Barton & Guestier
...,...,...,...,...,...,...,...,...,...,...,...,...,...
119578,France,"Warm and round, this Mâcon has ripe melon and ...",NaN,85,15.0,Burgundy,Mâcon-Villages,NaN,Roger Voss,@vossroger,Barton & Guestier 2011 Mâcon-Villages,Chardonnay,Barton & Guestier
122229,France,"This is a silky, ready-to-drink red. Cherry an...",Passeport,88,37.0,Rhône Valley,Châteauneuf-du-Pape,NaN,Joe Czerwinski,@JoeCz,Barton & Guestier 2013 Passeport Red (Châteaun...,Rhône-style Red Blend,Barton & Guestier
123273,France,"An attractive wine. The Chardonnay is fresh, l...",Cuvée Réservée Brut,85,10.0,France Other,Vin Mousseux,NaN,Roger Voss,@vossroger,Barton & Guestier NV Cuvée Réservée Brut Chard...,Chardonnay,Barton & Guestier
127672,France,This Margaux is full of firm tannins that para...,NaN,87,30.0,Bordeaux,Margaux,NaN,Roger Voss,@vossroger,Barton & Guestier 2010 Margaux,Bordeaux-style Red Blend,Barton & Guestier
129839,France,"Although initially austere, this wine then ope...",NaN,86,19.0,Bordeaux,Médoc,NaN,Roger Voss,@vossroger,Barton & Guestier 2006 Médoc,Bordeaux-style Red Blend,Barton & Guestier